### ISSUE TITLE
[Bug] NameError: undefined local variable or method `parent_station'

### ISSUE THREAD

**Issue by stephenyeargin** [sangster/gtfs_reader#6]
May be related to #4, but the GTFS feed for the Nashville MTA throws an exception when attempting to parse it.

```
NameError: undefined local variable or method `parent_station' for #<GtfsReader::ParserContext:0x007f993f8a40c8>
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:63:in `method_missing'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/config/defaults/gtfs_feed_definition.rb:38:in `block (4 levels) in <module:Defaults>'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:31:in `instance_exec'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:31:in `[]'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:45:in `block in to_hash'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:45:in `each'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:45:in `inject'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_row.rb:45:in `to_hash'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/file_reader.rb:45:in `each'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/feed_handler.rb:16:in `handle_file'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/source_updater.rb:176:in `process_from_temp_file'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/source_updater.rb:78:in `block in process_files'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/source_updater.rb:76:in `each'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/source_updater.rb:76:in `process_files'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/core.rb:54:in `block in update_verbosely'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/core.rb:48:in `instance_exec'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/core.rb:48:in `update_verbosely'
  /Users/yeargism/Sites/wego-bus-map/vendor/bundle/ruby/2.4.0/gems/gtfs_reader-1.2.0/lib/gtfs_reader/core.rb:34:in `update'
  bin/updateGtfsData:47:in `<top (required)>'

```

The [file in question](http://www.nashvillemta.org/GoogleExport/google_transit.zip) has null values for `parent_station`.

![screen shot 2018-09-17 at 2 14 08 pm](https://user-images.githubusercontent.com/80459/45644854-6c496980-ba84-11e8-8579-3618aea6e2e6.png)

**Comment by stephenyeargin** [comment]
This is the block of code I'm attempting to run.

```
# Configure the static parsing of GTFS feeds
GtfsSplitData = { trips: {}, shapes: {} }
GtfsConsolidatedData = { agency: {}, routes: {}, stops: {} }
GtfsReader.config do
  verbose true
  return_hashes true
  sources do
    default do
      url 'http://www.nashvillemta.org/GoogleExport/google_transit.zip'
      before { |etag| puts "Processing GTFS source with tag #{etag}..." }
      handlers do
        agency { |row| GtfsConsolidatedData[:agency][row[:agency_id]] = row }
        routes { |row| GtfsConsolidatedData[:routes][row[:route_id]] = row }
        stops { |row| GtfsConsolidatedData[:stops][row[:stop_id]] = row }
        shapes do |row|
          GtfsSplitData[:shapes][row[:shape_id]] = [] unless GtfsSplitData[:shapes][row[:shape_id]]
          GtfsSplitData[:shapes][row[:shape_id]] << row
        end
        trips { |row| GtfsSplitData[:trips][row[:trip_id]] = row }
      end
    end
  end
end

GtfsReader.update :default
```

**Comment by sangster** [comment]
Hi @stephenyeargin. Thanks kindly for such a detailed bug report! Apologies for the delay in my reply. I started a new job this week and it's eaten up much of my time this week.

I've release a new version of this gem: [v2.1.0](https://github.com/sangster/gtfs_reader/releases/tag/v2.1.0) ([RubyGem](https://rubygems.org/gems/gtfs_reader/versions/2.1.0)) which fixes this bug. Could you please `gem update gtfs_reader` and try your script again?

Thanks kindly!
